name = "automacao-issues-ai"
main = "cloudflare-app-worker.mjs"
compatibility_date = "2026-10-09"

[vars]
CLOUDFLARE_AI_MODEL = "@cf/meta/llama-3.3-70b-instruct-fp8-fast"
APP_BASE_URL = "https://automacao-issues-ai.automacao-issue-chico.workers.dev"

[ai]
binding = "AI"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "automatizador-db"
database_id = "12863ba9-ef91-4865-a029-5edbb2221dc8"
migrations_dir = "migrations"
