CREATE TABLE IF NOT EXISTS daily_usage (
  day TEXT PRIMARY KEY,
  requests INTEGER NOT NULL DEFAULT 0,
  rows_read INTEGER NOT NULL DEFAULT 0,
  rows_written INTEGER NOT NULL DEFAULT 0,
  neurons REAL NOT NULL DEFAULT 0,
  ai_calls INTEGER NOT NULL DEFAULT 0,
  ai_unknown INTEGER NOT NULL DEFAULT 0,
  ai_exhausted INTEGER NOT NULL DEFAULT 0,
  started_at INTEGER NOT NULL
);
